### ISSUE TITLE
Release for 7?

### ISSUE THREAD

**Issue by astrapi69** [WiQuery/wiquery#52] opened 2015-10-22 12:59 UTC
Hi there, in know this is a duplicate of #50 and #51 but there is no release in the mvn rep.

**Comment by martin-g** [comment] 2015-10-22 13:36
The last comments at #50 discuss how to release at Maven central repo (thru Sonatype OSS).
I think this issue is a duplicate of #50. There is no need to have several issues for the same task.

**Closed** 2015-10-23 10:48 UTC

**Comment by martin-g** [comment] 2015-11-01 18:39
Please see https://github.com/WiQuery/wiquery/pull/50#issuecomment-152851097
