### ISSUE TITLE
Release for 7?

### ISSUE THREAD

**Issue by gsmet** [WiQuery/wiquery#51] opened 2015-10-19 13:09 UTC
Hi,

Would it be possible to do an official release to Central for the Wicket 7 support?

Thanks!

**Comment by martin-g** [comment] 2015-10-19 13:44
Duplicate of #50

**Closed by martin-g** 2015-10-19 13:44 UTC

**Comment by martin-g** [comment] 2015-11-01 18:39
Please see https://github.com/WiQuery/wiquery/pull/50#issuecomment-152851097
